export const MCPE_PERFORMANCE_MODS = [
  {
    id: "mcpe-fps-optimizer",
    name: "FPS Optimizer | FPS Boost Official",
    title: "FPS Optimizer | FPS Boost Official",
    authors: [{ name: "XiaoCraft" }],
    author: "XiaoCraft",
    downloadCount: 1300000,
    download_count: 1300000,
    summary: "Two modes (Default / Max FPS), removes heavy particles, disables animated textures in Max mode. Highest download count of the bunch.",
    description: "Two modes (Default / Max FPS), removes heavy particles, disables animated textures in Max mode. Highest download count of the bunch.",
    category: "mods",
    version: "1.21.x",
    gameVersions: ["1.21.x"],
    thumbnail_url: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg",
    logoUrl: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg"
  },
  {
    id: "mcpe-vanilla-optimizer",
    name: "Vanilla × Optimizer FPS Boost",
    title: "Vanilla × Optimizer FPS Boost",
    authors: [{ name: "XiaoCraft" }],
    author: "XiaoCraft",
    downloadCount: 520000,
    download_count: 520000,
    summary: "Merges two optimizer packs into one; trims particles, animations, textures.",
    description: "Merges two optimizer packs into one; trims particles, animations, textures.",
    category: "mods",
    version: "1.21.x",
    gameVersions: ["1.21.x"],
    thumbnail_url: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg",
    logoUrl: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg"
  },
  {
    id: "mcpe-boosted-fps",
    name: "Boosted FPS (Optimized Performance)",
    title: "Boosted FPS (Optimized Performance)",
    authors: [{ name: "XiaoCraft" }],
    author: "XiaoCraft",
    downloadCount: 848000,
    download_count: 848000,
    summary: "Multiple subpacks (\"Pure FPS\" strips everything down for weakest devices), switchable in-game.",
    description: "Multiple subpacks (\"Pure FPS\" strips everything down for weakest devices), switchable in-game.",
    category: "mods",
    version: "1.21.x",
    gameVersions: ["1.21.x"],
    thumbnail_url: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg",
    logoUrl: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg"
  },
  {
    id: "mcpe-xiaoboost-ultimate",
    name: "XiaoBoost Ultimate",
    title: "XiaoBoost Ultimate",
    authors: [{ name: "XiaoCraft" }],
    author: "XiaoCraft",
    downloadCount: 142500,
    download_count: 142500,
    summary: "Combines four of their other packs into one all-in-one.",
    description: "Combines four of their other packs into one all-in-one.",
    category: "mods",
    version: "1.21.x",
    gameVersions: ["1.21.x"],
    thumbnail_url: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg",
    logoUrl: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg"
  },
  {
    id: "mcpe-fps-booster-pack",
    name: "FPS Booster Pack | No Lag + Performance",
    title: "FPS Booster Pack | No Lag + Performance",
    authors: [{ name: "XiaoCraft" }],
    author: "XiaoCraft",
    downloadCount: 219600,
    download_count: 219600,
    summary: "Reduced texture/particle load, lightweight fog/sky.",
    description: "Reduced texture/particle load, lightweight fog/sky.",
    category: "mods",
    version: "1.21.x",
    gameVersions: ["1.21.x"],
    thumbnail_url: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg",
    logoUrl: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg"
  },
  {
    id: "mcpe-fps-booster-lag-fix",
    name: "FPS Booster | Lag Fix",
    title: "FPS Booster | Lag Fix",
    authors: [{ name: "RisabGamerz" }],
    author: "RisabGamerz",
    downloadCount: 858000,
    download_count: 858000,
    summary: "One of the highest-downloaded standalone boosters.",
    description: "One of the highest-downloaded standalone boosters.",
    category: "mods",
    version: "1.21.x",
    gameVersions: ["1.21.x"],
    thumbnail_url: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg",
    logoUrl: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg"
  },
  {
    id: "mcpe-fps-booster-no-lag",
    name: "FPS Booster (No Lag & FPS Boost)",
    title: "FPS Booster (No Lag & FPS Boost)",
    authors: [{ name: "RisabGamerz" }],
    author: "RisabGamerz",
    downloadCount: 384000,
    download_count: 384000,
    summary: "An earlier/alt version of the FPS Booster | Lag Fix.",
    description: "An earlier/alt version of the FPS Booster | Lag Fix.",
    category: "mods",
    version: "1.21.x",
    gameVersions: ["1.21.x"],
    thumbnail_url: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg",
    logoUrl: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg"
  },
  {
    id: "mcpe-fps-booster-pvp",
    name: "FPS Booster (No Lag And FPS Boost)",
    title: "FPS Booster (No Lag And FPS Boost)",
    authors: [{ name: "Unknown" }],
    author: "Unknown",
    downloadCount: 83800,
    download_count: 83800,
    summary: "Marketed toward PvP specifically.",
    description: "Marketed toward PvP specifically.",
    category: "mods",
    version: "1.21.x",
    gameVersions: ["1.21.x"],
    thumbnail_url: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg",
    logoUrl: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg"
  },
  {
    id: "mcpe-performance-plus",
    name: "Performance+",
    title: "Performance+",
    authors: [{ name: "HoneyStudios" }],
    author: "HoneyStudios",
    downloadCount: 90700,
    download_count: 90700,
    summary: "Framed as keeping a \"vanilla\" look while trimming render load — good option if you want a less aggressive/more visually clean pick.",
    description: "Framed as keeping a \"vanilla\" look while trimming render load — good option if you want a less aggressive/more visually clean pick.",
    category: "mods",
    version: "1.21.x",
    gameVersions: ["1.21.x"],
    thumbnail_url: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg",
    logoUrl: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg"
  },
  {
    id: "mcpe-ultimate-fps-booster",
    name: "ULTIMATE FPS BOOSTER",
    title: "ULTIMATE FPS BOOSTER",
    authors: [{ name: "FoxyFall" }],
    author: "FoxyFall",
    downloadCount: 104100,
    download_count: 104100,
    summary: "Focuses on UI/rendering/visual effects optimization.",
    description: "Focuses on UI/rendering/visual effects optimization.",
    category: "mods",
    version: "1.21.x",
    gameVersions: ["1.21.x"],
    thumbnail_url: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg",
    logoUrl: "https://media.forgecdn.net/avatars/417/99/637651036735237894.jpeg"
  }
];
