// lib/seoWhitelist.js
// AUTO-GENERATED by scripts/buildWhitelist.mjs — do not edit manually.
// Re-run: node scripts/buildWhitelist.mjs
// Generated: 2026-07-10T06:58:03.001Z
// Count: 500 unique CurseForge project IDs

/**
 * The ≤500 VIP CurseForge project IDs whose /resource/[id] pages
 * should be indexed by search engines. All other resource pages
 * are noindexed to concentrate crawl budget.
 */
export const SEO_WHITELIST = [
  238222, // Just Enough Items (JEI)
  32274, // JourneyMap
  328085, // Create
  261166, // Clumps
  248787, // AppleSkin
  223852, // Mouse Tweaks
  245733, // Waystones
  252865, // Nature's Compass
  250398, // Controlling
  361579, // Spark
  422301, // Sophisticated Backpacks
  220318, // Biomes O' Plenty
  230911, // Fast Leaf Decay
  238529, // Gravestone Mod
  306612, // Fabric API
  394468, // Sodium
  455508, // Iris Shaders
  360438, // Lithium
  459857, // Mod Menu
  308702, // Storage Drawers
  534063, // Fresh Animations
  220919, // Sphax PureBDcraft
  348074, // Bare Bones
  349275, // Stay True
  477174, // Faithless
  341053, // Clarity
  224675, // John Smith Legacy
  326848, // Dramatic Sky
  318359, // Xray Ultimate
  501625, // Patrix
  250146, // Vanilla Tweaks
  291364, // Xali's Bushy Leaves (estimated)
  813295, // Complementary Shaders - Unbound
  953118, // Complementary Shaders - Rebound
  272370, // BSL Shaders
  252179, // Sildur's Vibrant Shaders
  552697, // AstraLex Shaders
  379899, // Kappa Shaders
  687223, // Rethinking Voxels
  853412, // Bliss Shader
  933068, // Pastel Shaders
  535684, // Complementary Reimagined
  239399, // SEUS (Sonic Ether's Unbelievable Shaders)
  443929, // Photon Shader
  1179976, // Newb Shader
  1246506, // Newb X Dawn Shader
  1246515, // Newb Complementary Shader
  1246521, // Newb X Ale
  1248967, // Newb X Stars Shader
  1174285, // iOS Newb X LMI
  60089, // Mouse Tweaks
  228525, // Bookshelf
  388172, // GeckoLib
  348521, // Cloth Config API (Fabric/Forge/NeoForge)
  256717, // Clumps
  419699, // Architectury API
  283644, // Placebo
  245755, // Waystones
  309927, // Curios API (Forge/NeoForge)
  252848, // Nature's Compass
  306770, // Patchouli
  250419, // Enchantment Descriptions
  499980, // Moonlight Lib
  243121, // Quark
  324717, // Jade 🔍
  342584, // Collective
  272515, // Better Advancements
  240630, // Just Enough Resources (JER)
  531761, // Balm
  276951, // Comforts
  263420, // Xaero's Minimap
  404465, // FTB Library (NeoForge)
  239197, // CraftTweaker
  74924, // Mantle
  398521, // Farmer's Delight
  223794, // Applied Energistics 2
  250363, // AutoRegLib
  280510, // AttributeFix
  790626, // ModernFix
  228756, // Iron Chests
  412082, // Supplementaries
  429235, // FerriteCore ((Neo)Forge)
  410295, // Konkrete
  388800, // Polymorph (Fabric/Forge/Quilt)
  289412, // FTB Quests (NeoForge)
  274259, // Carry On
  448233, // Entity Culling Fabric/Forge
  404468, // FTB Teams (NeoForge)
  257814, // CreativeCore
  367706, // FancyMenu
  317780, // Xaero's World Map
  227639, // The Twilight Forest
  453763, // Fresh Animations
  226375, // Xray Ultimate
  353554, // Stay True
  664719, // Mandala's GUI - Dark mode
  380969, // Motschen's Better Leaves
  580036, // Enhanced Boss Bars
  538850, // Eclectic Trove (Legendary Tooltips)
  312822, // Tissou's Zombie Pack
  860903, // Fresh Waystones Texture
  554331, // Repurposed Structures - Farmer's Delight Compat Datapack
  827281, // When Dungeons Arise - No Flying Structures
  827727, // When Dungeons Arise - Spacing Tweaks
  888795, // Icon Xaero's
  990406, // Fresh Moves
  231821, // Dramatic Skys
  813608, // Fresh Animations: Extensions
  592278, // Repurposed Structures - Friends and Foes Compat Datapack
  580181, // Slightly Improved Font (32x)
  853631, // When Dungeons Arise - Loot Tweaks
  503839, // Embellished Stone (Advancement Plaques)
  326818, // Excalibur
  943485, // Backpacked Recipe Fix
  390367, // The Pixelmon Mod OST
  478165, // xali's Enchanted Books
  376145, // Leviosa
  554329, // Repurposed Structures - Better Dungeons Compat Datapack
  547822, // Repurposed Structures - Better Strongholds Compat Datapack
  580683, // Low On Fire
  864002, // Aether: Regenerated
  349116, // Default Dark Mode
  326400, // Lycanites Mobs 32X
  517821, // Animated And Emissive: Ice and Fire and Spartan Weaponry
  882133, // Boss Refreshed
  634440, // Repurposed Structures - Better Witch Huts Compat Datapack
  920757, // Sky Villages - Waystones Compat
  884709, // (Bee's) Fancy Crops
  825234, // Repurposed Structures - VillagerPlus Compat Datapack
  455845, // STONEBORN - Dwarven-Fantasy Inspired UI Overhaul
  920761, // Sky Villages - Supplementaries Compat
  468836, // Created Simple Storage Network
  965613, // Scarecrow Obliterator | Datapack
  934914, // Sky Villages - Farmer's Delight Compat
  571281, // Repurposed Structures - Bountiful Compat Datapack
  776419, // Tom's Create Storage
  844259, // Repurposed Structures - Bygone Nether Compat Datapack
  679106, // Visual Traveler's Titles
  577462, // Excalibur Mod Support
  422825, // Visible Ores
  489807, // Lum (Backport)
  899330, // Create Style Sophisticated Backpacks
  627557, // Complementary Shaders - Reimagined
  385587, // Complementary Shaders - Unbound
  322506, // BSL Shaders
  431203, // MakeUp - Ultra Fast | Shaders
  544096, // Sildur's Vibrant shaders
  678384, // Solas Shader
  610844, // Bliss Shaders
  618217, // 🎃 Insanity Shader
  813185, // Pastel Shaders
  534748, // Super Duper Vanilla Shaders
  1040578, // 👻 Hysteria Shaders
  921717, // Spooklementary
  1113130, // Mellow
  406081, // AstraLex Shaders
  467280, // Potato Shader
  326302, // Nostalgia Shader
  322270, // Kappa Shader
  544140, // Sildur's Enhanced Default Shaders
  322360, // Vanilla Plus Shader
  273654, // Beyond Belief Shaders
  602290, // Miniature Shader
  1312687, // Photon Shader
  363825, // UShader
  654153, // Sildur's Basic Shaders
  449652, // RedHat Shaders v34.3
  345953, // Simplicissimus Shader
  1085570, // BSL Shaders - Classic
  1093481, // Body Camera Shader
  486209, // Voyager shader 2.0
  855381, // FastPBR Shader
  340099, // Oceano Shaders 3.0
  759541, // Noble Shaders
  1159841, // Cursed Fog
  331780, // Tea Shaders
  1155908, // E-LITE shaders (MakeUp edit)
  1248172, // Reverie
  897289, // CTMPOMFIX Shader  (Chocapic13' Shaders edit)
  1230724, // Pyvtron Shaders
  832754, // Shrimple
  1038016, // Simply Upscaled
  978510, // Skygleam Shaders
  1204051, // Just Colored Lighting
  669144, // Soft Voxels Lite
  338898, // Exposa Shaders
  1333879, // Fantasy Shaders Reimagined
  78226, // PlunderPixel's Shader Reimagined
  1092607, // Pegasus Shaders 
  648063, // Arc [shader]
  1167228, // CTR VCR
  995473, // I Like Vanilla
  1244801, // Visual Vibrance
  478295, // Prismarine Shader
  954161, // TerraFirmaGreg-Shaders
  883885, // Pixel Perfect Shaders
  569743, // Stracciatella Shaders
  923458, // Light Shaders
  758336, // OPAL Shaders
  961015, // MCSX PSX Custom Shader
  992520, // Night Visions Shaders [Java]
  1058040, // RetroVision
  1248396, // RenderPearl
  341332, // Sunflawer Shaders
  1307521, // TrueLightFX Lite
  1065471, // Muuf A.G.I Shaders
  1270940, // VHS Overlay
  969143, // Vanilletix Shaders
  1017185, // Legendary Atmosphere
  1328330, // Eclipse
  1348190, // DERCODE
  1259464, // TrueLight FX
  331885, // RRe36's Shader
  1462750, // Aurora Fantasy
  863609, // Lux V1
  1191468, // PixelCraft Shaders
  1277376, // Amethyst Shaders
  1257984, // Bloop Shaders - Official
  996289, // CH Motion
  1353097, // Luminara Shader
  1376551, // Kute
  914435, // Energy Shaders [Java]
  1321365, // Vanilla Enhanced
  1329030, // Pyvtron VX
  1414712, // PSX-Core Shader
  920167, // Monophonic Shaderpack
  1091924, // Motion Blur FX
  1186108, // Ethereal Shaders
  1412914, // Spring Shaders (Chun)
  1160103, // TheShader
  1200398, // Complementary Unbound - edition HardRock TFC
  1159839, // BVS - Best Shader
  1167533, // Glimmer Shaders
  1414000, // Soft Memory
  907507, // Boovlermentary
  1118927, // Optimism-shader
  337167, // Windom Shaders
  1400476, // Luminara Shader - Rebuilt
  1512050, // FOOTAGE
  1440736, // Raincore
  1411133, // LiDAR-S
  1481177, // Lumina Shaders - Event Horizon
  1282905, // Crucify
  1424265, // Author87668's LIGHT Shaders
  1331066, // Anti Aliasing (TAA, FXAA)
  1402616, // Zayko Shaders
  1490563, // Lumina Shader - Lite
  1382980, // SCAN
  1338768, // i hate shadows
  1377309, // Cartoony
  1372310, // Miasma
  1324980, // bybyshader
  1401608, // Reflexa
  988064, // PwC Retro Pixels Shaders
  1384822, // Luminara Shader spooky
  1248471, // SMAA-Iris
  1329060, // Five Nights at Pixels Shader Edition
  1384842, // PureCraft Shader
  1317946, // Loé's Night Vision
  1348314, // Blocky Shader
  1377347, // Blind
  1229198, // Outline Shader
  1320231, // Cursed View
  1324974, // msf
  1028104, // Phoxel PT
  1368495, // Low Water
  1333373, // Cartoonikal
  1401753, // Sunveil
  1382372, // SI: Spectre [DISCONTINUED]
  1377353, // Cozy & Light
  1313908, // Spectrum Shaders
  1451748, // VHS Shader
  1469001, // Color Cone
  1297650, // Escheridia
  1343657, // ✏️SketchBound
  1422575, // Dithering3D
  1329921, // Grayscale Lightmap
  1040084, // Shaders for  Advanced Rocketry
  1423120, // Wispy Shader
  1356891, // Pretty Shadows
  1387743, // Shadolimetto
  1468485, // Aurora
  625267, // Sildurs Shaders TFC setup 
  1489698, // Reflectify RT— Realistic Rain & Mirror Ice (SSR & God Rays)
  1275107, // GlacierShaders
  1445997, // Alpha Piscium
  1362054, // Complementary RU translation (Русификатор)
  1389097, // Clarity
  1468879, // DERCODE Lite
  1373474, // Chippa256 Shaders
  1586359, // Verity Shader
  1240626, // PSX Shader NB
  1499916, // Colorfull ✨
  1183387, // lobotomy shader
  1522455, // Colorfull Reimagined 🍂✨
  960820, // CilokGaming Shaders v1.0
  1503360, // Colorfull Unbound 🌈✨
  1517489, // ARTShade
  1399624, // Dynamic Lights Shader
  1279949, // AstralCore
  1222752, // BDS - Better Default Shaders
  1029875, // PwC Deep Fried Shaders
  1345898, // Epic Fight Glowing Light Trail
  1374991, // DreamLight Shaders
  1503535, // LiDAR Visualizer
  1022532, // Skylec
  1515541, // HighFrames
  1353845, // Luminara Shader Lite
  1514207, // B&W Shader
  1007818, // SWS
  1421242, // PROMO SHADER
  1483899, // OldNightmares Shader
  1546182, // ColorFull Optimized ✨⚡
  1135089, // BloodyShaders
  1089016, // Neon Skylines Shader
  1322974, // Javier's improved fog
  1587395, // RETRO_VHS_Screen
  555000, // SimpleTAA Shaderpack
  1055565, // Ascii like shader
  1524035, // only shadows
  1473343, // Found Footage
  1148430, // Fancy Complements
  1293199, // Fisheye Shaders
  1109406, // Snow Default
  1541827, // Mini Shaders
  1387076, // Atmospheric Shaders
  1113645, // Emoji like shader
  1069410, // PwC Outline Shaders
  1538468, // Post'n'Stuff!
  1507897, // retroview
  1214535, // Oct-Path
  1086316, // CRT Shader
  1369402, // Butter Shaders
  1167205, // Ink Shader
  1542089, // Black And White Shaders
  1116362, // Spook
  1542726, // N87 Shaders
  1075266, // Negative Colors
  1222753, // DMS - Depth Map Shaders
  1275118, // CoffeeShaders
  1291167, // True Black & White Shader (Grayscale)
  1531192, // Earth Shaders
  288885, // FastWorkbench
  581495, // Oculus
  686911, // ImmediatelyFast
  299540, // FastFurnace
  278494, // Foam​Fix
  475117, // FastSuite
  908741, // Embeddium
  663477, // Let Me Despawn
  949555, // BadOptimizations
  1091339, // AllTheLeaks (Memory Leak Fix)
  1154099, // Crash Assistant
  574856, // Rubidium
  551736, // Sodium/Embeddium Dynamic Lights
  570017, // Radium Reforged
  526854, // Starlight (Forge)
  550579, // ServerCore
  659897, // Iris & Oculus Flywheel Compat
  558905, // Sodium/Embeddium Extras
  931925, // Chloride (Previously Embeddium++/Sodium++)
  877289, // Redirector [Modern]
  840788, // CullLessLeaves Reforged (Unofficial)
  985426, // Particle Core
  1087831, // Structure Layout Optimizer
  630104, // MoreCulling
  821790, // Lightspeed - Launch optimizations
  521783, // Starlight (Fabric)
  1079896, // CrashExploitFixer
  974401, // Mobtimizations - Entity Performance Fixes
  409087, // Entity Culling
  1254143, // Colorwheel
  1142875, // Flerovium
  905468, // DespawnTweaker
  1030285, // FastBoot
  1210171, // Fast Item Frames
  1217518, // Create Better FPS
  564239, // Xenon
  983390, // Simple Weather
  970291, // Temporal API
  825355, // DoesPotatoTick?
  1167848, // Distraction Free Recipes (EMI / REI / JEI)
  399022, // Spawner Bug Fix
  419286, // MixinBooter
  624967, // RenderLib
  905450, // Bocchium
  1163206, // Immersive Optimization
  267602, // ConnectedTexturesMod
  495476, // Puzzles Lib
  231484, // Cooking for Blockheads
  237307, // Cosmetic Armor Reworked
  618298, // Sophisticated Core
  74072, // Tinkers Construct
  69162, // CoFH Core
  326652, // Cupboard
  351264, // Kotlin for Forge
  271740, // Toast Control
  309674, // Item Filters
  233105, // McJtyLib
  331936, // Citadel
  454372, // SuperMartijn642's Core Lib
  242818, // CodeChicken Lib 1.8.+
  230976, // Fast Leaf Decay
  421850, // YUNG's API (Forge/NeoForge)
  250832, // OpenBlocks Elevator
  233071, // Crafting Tweaks
  438332, // SuperMartijn642's Config Lib
  225643, // Botania
  272335, // Cucumber Library
  232131, // Default Options
  570073, // Resourceful Lib
  268560, // Mekanism
  235279, // Chisel
  222880, // Thermal Foundation
  231951, // Immersive Engineering
  416294, // Rhino
  389665, // YUNG's Better Mineshafts (Forge/NeoForge)
  254268, // Torchmaster
  658587, // playerAnimator
  60028, // Aquaculture 2
  858542, // Searchables
  241160, // NetherPortalFix
  225738, // MmmMmmMmmMmm (Target Dummy)
  238086, // KubeJS
  232758, // Cyclops Core
  361276, // Lootr (Forge & NeoForge)
  520110, // Iceberg [Neo/Forge]
  470193, // Connectivity
  243076, // Refined Storage
  563928, // TerraBlender (Forge)
  298187, // Building Gadgets
  233019, // AI Improvements
  433760, // Not Enough Animations
  266515, // Industrial Foregoing
  351725, // Macaw's Bridges
  69163, // Thermal Expansion
  268566, // Mekanism Generators
  308989, // Caelus API
  246640, // Mystical Agriculture
  242195, // Dark Utilities
  231095, // Chisels & Bits - For Forge
  568563, // [ETF] Entity Texture Features - [Fabric & Forge]
  223094, // Inventory Tweaks [1.12 only] 
  312353, // Artifacts
  226406, // Custom Main Menu
  535489, // Sound Physics Remastered
  938643, // Melody
  244844, // ForgeEndertech
  248020, // Flux Networks
  248453, // Shadowfacts' Forgelin
  313970, // Apotheosis
  549225, // Framework
  237749, // CoroUtil
  64578, // Ender IO
  844662, // [EMF] Entity Model Features [Fabric & Forge]
  260912, // XNet
  314906, // FTB Chunks (NeoForge)
  226447, // Resource Loader
  69118, // Morpheus
  316582, // Corpse
  245174, // Ender Storage 1.8.+
  55438, // MrCrayfish's Furniture Mod (Legacy)
  70496, // BdLib
  238372, // Neat
  254284, // AmbientSounds 6
  261251, // Bad Wither No Cookie - Reloaded
  227083, // Baubles
  378646, // Macaw's Doors
  457570, // Configured
  241895, // KleeSlabs
  235577, // TrashSlot
  510089, // YUNG's Better Dungeons (Forge/NeoForge)
  714059, // Resourceful Config
  889915, // FTB XMod Compat
  247007, // Common Capabilities
  582327, // Server Performance - Smooth Chunk Save
  317716, // Elytra Slot
  261924, // Farming for Blockheads
  236307, // Integrated Dynamics
  363569, // Macaw's Windows
  256247, // Mystical Agradditions
  237701, // ReAuth
  634062, // No Chat Reports
  220954, // ModTweaker
  268567, // Mekanism Tools
  551894, // Better Compatibility Checker
  416089, // Simple Voice Chat
  386134, // FTB Ultimine (NeoForge)
  382216, // Blueprint
  227443, // Thermal Dynamics
  401955, // Ars Nouveau
  224791, // Blood Magic 
  426558, // Alex's Mobs
  511770, // Drippy Loading Screen
  225561, // Extra Utilities
  229060, // iChunUtil
  291874, // Serene Seasons
  378802, // Structure Gel API
  667299, // YetAnotherConfigLib
  453925, // Macaw's Fences and Walls
];

/**
 * O(1) lookup Set for checking whitelist membership.
 * Usage: SEO_WHITELIST_SET.has(Number(id))
 */
export const SEO_WHITELIST_SET = new Set(SEO_WHITELIST);
